version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    ports:
      # we need to expose the port to the host, but as we may also have local ollama running, we need to use a different port
      - "51134:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./Modelfile:/Modelfile
    environment:
      - OLLAMA_SKIP_CUDA=1
      - OLLAMA_VERBOSE=false
      - LOG_LEVEL=error
      - OLLAMA_RETRY_MAX=2
      - OLLAMA_TIMEOUT=60s
      - OLLAMA_KEEP_ALIVE=60s
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - ollama-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "ollama-service"
        env: "production"
        tag: "{{.Name}}"
  init-ollama:
    build:
      context: .
      dockerfile: Dockerfile.init
    volumes:
      - ./init-ollama.sh:/init-ollama.sh
      - ./Modelfile:/Modelfile
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_SKIP_CUDA=1
    depends_on:
      ollama:
        condition: service_healthy
    command: /init-ollama.sh
    networks:
      - ollama-network

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: agent
    ports:
      - "7860:7860"
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - OLLAMA_SKIP_CUDA=1
    depends_on:
      init-ollama:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge

volumes:
  ollama_data: