FROM ollama/ollama:latest

# curl for healthcheck
RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV OLLAMA_VERBOSE=false
ENV LOG_LEVEL=error 